name: publish
on: [push]
jobs:
  publish-cbla-base-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the cbla-base Docker image
      run: |
         docker build . --tag ghcr.io/cbajapan/cbla-base:latest
         docker run ghcr.io/cbajapan/cbla-base:latest
         docker push ghcr.io/cbajapan/cbla-base:latest
